SECTION_KIND_SHARE = 1
SECTION_KIND_PRESENT = 10
SECTION_KIND_ETN = 17

STOCKCHART_DAY_CODE = 0 # 날짜
STOCKCHART_OPENING_QUTATION_CODE = 2 # 시가
STOCKCHART_HIGHEST_QUTATION_CODE = 3 # 고가
STOCKCHART_LOWEST_QUTATION_CODE = 4 # 저가
STOCKCHART_CLOSING_QUTATION_CODE = 5 # 종가
STOCKCHART_TRADING_QUTATION_CODE = 8 # 거래량
STOCKCHART_MARKET_CAPITALIZATION_CODE = 13 # 시가총액

STOCKCHART_CHARTTYPE_DAY_CODE = ord('D')
STOCKCHART_CHARTTYPE_WEEK_CODE = ord('W')
STOCKCHART_CHARTTYPE_MONTH_CODE = ord('M')
STOCKCHART_CHARTTYPE_MIN_CODE = ord('m')
STOCKCHART_CHARTTYPE_TICK_CODE = ord('T')

MARKETEYE_PRICE_CODE = 4 # 현재가
MARKETEYE_PER_CODE = 67 # PER
MARKETEYE_EPS_CODE = 70 # EPS
MARKETEYE_CAPITAL = 71 # 자본금
MARGETEYE_DEPT_RATIO = 75 # 부채 비율
MARKETEYE_BPS_CODE = 89 # BPS
MARKETEYE_REAL_PROFIT = 91 # 영업 이익
MARKETEYE_NEAREST_MONTH_CODE = 111 # 최근 분기 년월


NAVER_NAME = 'NAVER'

INDUSTRY_CODE_TOTAL_POINT = 1
INDUSTRY_CODE_BIG_STOCK = 2
INDUSTRY_CODE_MID_STOCK = 3
INDUSTRY_CODE_SMALL_STOCK = 4
INDUSTRY_CODE_FOOD = 5
INDUSTRY_CODE_CLOTHES = 6
INDUSTRY_CODE_PAPER = 7
INDUSTRY_CODE_CHEM = 8
INDUSTRY_CODE_MEDI = 9
INDUSTRY_CODE_NONMETAL = 10
INDUSTRY_CODE_METAL = 11
INDUSTRY_CODE_MACHINE = 12
INDUSTRY_CODE_ELECT = 13
INDUSTRY_CODE_SMALL_MEDI = 14
INDUSTRY_CODE_TRANSPORT_MACHINE = 15
INDUSTRY_CODE_TRANSPORT = 16
INDUSTRY_CODE_SERVICE = 26
INDUSTRY_CODE_MANUFACTURE = 27


TRADE_TYPE_DESIGNATION = '01' # 지정가 주문
TRADE_TYPE_BEST = '12' # 최유리 주문
TRADE_TYPE_FIRST = '13' # 최우선 주문
